version: '3'
services:
  ruby:
    image: hello-world
    ports:
      - "3000:3000"
    volumes:
      - ./code:/code
      - cache-data:/cache
    working_dir: /code
    command: bash
    tty: true

volumes:
  cache-data:
