version: '3'

services:
  app:
    image: python:3.6
    command: python manage.py runserver 0:8000
    environment:
      DEBUG: 1
      PYTHONUNBUFFERED: 1
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - pip-bin-data:/usr/local/bin
      - pip-data:/usr/local/lib/python3.6/site-packages
    working_dir: /code
    depends_on:
      - db
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pip-bin-data:
  pip-data:
  pg-data:
