version: '3'

services:
  app:
    image: ruby
    command: rails s -b 0
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/code
      - gem-data:/usr/local/bundle
    working_dir: /code
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  gem-data:
  pg-data:
