version: "3"

services:
  app:
    build: .
    command: rails s -b 0
    depends_on:
      - db
    environment:
      DB_HOST: db
      LANG: C.UTF-8
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - "3000:3000"
      - "3035:3035"
    volumes:
      - .:${PWD}
      - ./.docker/.gemrc:/root/.gemrc
      - gem-data:/usr/local/bundle
      - yarn-data:/usr/local/share/.cache/yarn/v2
    working_dir: ${PWD}
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  gem-data:
  pg-data:
  yarn-data:
