version: '3'

services:
  app:
    image: ruby
    command: rails s -b 0
    depends_on:
      - db
    environment:
      DB_HOST: db
      LANG: C.UTF-8
    ports:
      - '3000:3000'
    volumes:
      - .:${PWD}
      - ./.docker/.gemrc:/root/.gemrc
      - gem-data:/usr/local/bundle
    working_dir: ${PWD}
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  ? gem-data
  ? pg-data
