version: "3"

services:
  app: &app
    image: circleci/ruby:2.7-node
    # for system test
    # image: circleci/ruby:2.7-node-browsers
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/rails s -b 0"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      LANG: C.UTF-8
      WEBPACKER_DEV_SERVER_HOST: webpacker
    ports:
      - "3000:3000"
    user: root
    volumes:
      - .:${PWD}
      - ./.docker/.gemrc:/root/.gemrc
      - gem-data:/usr/local/bundle
      - yarn-data:/usr/local/share/.cache/yarn
    working_dir: ${PWD}
  db:
    image: postgres:alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    depends_on: []
    environment:
      WEBPACKER_DEV_SERVER_HMR: "true"
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - "3035:3035"

volumes:
  gem-data:
  pg-data:
  yarn-data:
